# Traefik Static Configuration

accesslog:
  filePath: "/logs/access.log"

providers:
  file:
    directory: /etc/traefik
    watch: true
  docker:
    exposedByDefault: true

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  stackresolver:
    acme:
      storage: "/letsencrypt/acme.json"
      tlsChallenge: true
      httpChallenge:
        entryPoint: websecure

experimental:
  plugins:
    geoblock:
      modulename: github.com/PascalMinder/geoblock
      version: v0.2.7
    denyip:
      modulename: github.com/kevtainer/denyip
      version: v1.0.0
