# Traefik dynamic configuration

http:
  middlewares:
    usonly:
      plugin:
        geoblock:
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          cacheSize: 14
          silentStartUp: false
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: false
          logApiRequests: false
          forceMonthlyUpdate: true
          blackListMode: false
          countries:
            - US
    topten:
      plugin:
        geoblock:
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          cacheSize: 14
          silentStartUp: false
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: false
          logApiRequests: false
          blackListMode: true
          forceMonthlyUpdate: true
          countries:
            - CH
            - RU
            - RO
            - BR
            - IN
            - IR
            - VN
            - TR
            - TH
            - ID
            
